import js from '@eslint/js';
import eslintConfigPrettier from 'eslint-config-prettier';
import eslintPluginPrettier from 'eslint-plugin-prettier';
import nextPlugin from '@next/eslint-plugin-next';
import typescriptParser from '@typescript-eslint/parser';
import typescriptPlugin from '@typescript-eslint/eslint-plugin';

export default [
  // PRIMEIRO: Configuração de ignores (deve vir antes)
  {
    ignores: [
      '**/.next/**',
      'node_modules/**',
      'out/**',
      'dist/**',
      'coverage/**',
      'next-env.d.ts',
      '**/*.config.js',
    ],
  },
  // SEGUNDO: Configurações recomendadas
  js.configs.recommended,
  // TERCEIRO: Configuração principal
  {
    files: ['**/*.ts', '**/*.tsx', '**/*.js', '**/*.jsx'],
    languageOptions: {
      parser: typescriptParser,
      parserOptions: {
        ecmaVersion: 'latest',
        sourceType: 'module',
        ecmaFeatures: {
          jsx: true,
        },
      },
      globals: {
        React: 'readonly',
        fetch: 'readonly',
        document: 'readonly',
        window: 'readonly',
        console: 'readonly',
        setTimeout: 'readonly',
        setInterval: 'readonly',
        clearTimeout: 'readonly',
        clearInterval: 'readonly',
        alert: 'readonly',
        process: 'readonly',
        Buffer: 'readonly',
        Request: 'readonly',
        Response: 'readonly',
        URL: 'readonly',
        File: 'readonly',
        FormData: 'readonly',
        AbortController: 'readonly',
        IntersectionObserver: 'readonly',
        MutationObserver: 'readonly',
        HTMLInputElement: 'readonly',
        HTMLDivElement: 'readonly',
        HTMLElement: 'readonly',
        MouseEvent: 'readonly',
        DragEvent: 'readonly',
        Node: 'readonly',
        TextEncoder: 'readonly',
        crypto: 'readonly',
        TextDecoder: 'readonly',
        Blob: 'readonly',
        FileReader: 'readonly',
        URLSearchParams: 'readonly',
        Headers: 'readonly',
        ReadableStream: 'readonly',
        navigator: 'readonly',
        location: 'readonly',
        performance: 'readonly',
        atob: 'readonly',
        btoa: 'readonly',
        Element: 'readonly',
        Node: 'readonly',
        HTMLElement: 'readonly',
        getComputedStyle: 'readonly',
        MutationObserver: 'readonly',
        IntersectionObserver: 'readonly',
        ResizeObserver: 'readonly',
        AbortController: 'readonly',
        AbortSignal: 'readonly',
        Event: 'readonly',
        MessageChannel: 'readonly',
        MessagePort: 'readonly',
        queueMicrotask: 'readonly',
        reportError: 'readonly',
        structuredClone: 'readonly',
        BroadcastChannel: 'readonly',
        CSS: 'readonly',
        DOMRect: 'readonly',
        HTMLScriptElement: 'readonly',
        WebAssembly: 'readonly',
        importScripts: 'readonly',
        self: 'readonly',
      },
    },
    plugins: {
      '@typescript-eslint': typescriptPlugin,
      prettier: eslintPluginPrettier,
      '@next/next': nextPlugin,
    },
    rules: {
      'prettier/prettier': 'error',
      '@typescript-eslint/no-unused-vars': [
        'warn',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
        },
      ],
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-empty-object-type': 'off',
      '@typescript-eslint/ban-ts-comment': 'off',
      'no-undef': 'off',
      'no-unused-expressions': 'off',
      'no-fallthrough': 'off',
      'no-cond-assign': 'off',
      'no-empty': 'off',
      'no-prototype-builtins': 'off',
      'no-control-regex': 'off',
      'no-constant-condition': 'off',
      'no-unused-vars': 'off',
      'no-self-assign': 'off',
      'no-func-assign': 'off',
      'no-case-declarations': 'off',
      'getter-return': 'off',
      'valid-typeof': 'off',
      'no-misleading-character-class': 'off',
    },
    settings: {
      react: {
        version: 'detect',
      },
      next: {
        rootDir: './',
      },
    },
  },
  eslintConfigPrettier,
];
